<a href="https://colab.research.google.com/github/naveenvarma600/MovieRecommender/blob/main/MovieRecommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's import the necessary libraries and load the data now.

In [1]:
import pandas as pd 
import numpy as np 
df1=pd.read_csv('tmdb_5000_credits.csv')
df2=pd.read_csv('tmdb_5000_movies.csv')

The first dataset contains the following features:-             

**movie_id** - A unique identifier for each movie.              
**cast** - The name of lead and supporting actors.             
**crew** - The name of Director, Editor, Composer, Writer etc.             

The second dataset has the following features:-           

**budget** - The budget in which the movie was made.           
**genre** - The genre of the movie, Action, Comedy ,Thriller etc.           
**homepage** - A link to the homepage of the movie.           
**id** - This is infact the movie_id as in the first dataset.           
**keywords** - The keywords or tags related to the movie.           
**original_language** - The language in which the movie was made.
**original_title** - The title of the movie                     
**overview** - A brief description of the movie.           
**popularity** - A numeric quantity specifying the movie popularity.           
**production_companies** - The production house of the movie.           
**production_countries** - The country in which it was produced.           
**release_date** - The date on which it was released.           
**revenue** - The worldwide revenue generated by the movie.           
**runtime** - The running time of the movie in minutes.           
**status** - "Released" or "Rumored".           
**tagline** - Movie's tagline.           
**title** - Title of the movie.           
**vote_average** - average ratings the movie recieved.           
**vote_count** - the count of votes recieved.

In [2]:
df1.columns = ['id','tittle','cast','crew']
df2= df2.merge(df1,on='id')

In [3]:
df2.head(5)

      budget  ...                                               crew
0  237000000  ...  [{"credit_id": "52fe48009251416c750aca23", "de...
1  300000000  ...  [{"credit_id": "52fe4232c3a36847f800b579", "de...
2  245000000  ...  [{"credit_id": "54805967c3a36829b5002c41", "de...
3  250000000  ...  [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4  260000000  ...  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

[5 rows x 23 columns]

In [4]:
df2['overview'].head(5)

0    In the 22nd century, a paraplegic Marine is di...
1    Captain Barbossa, long believed to be dead, ha...
2    A cryptic message from Bondâ€™s past sends him o...
3    Following the death of District Attorney Harve...
4    John Carter is a war-weary, former military ca...
Name: overview, dtype: object

In [5]:

from sklearn.feature_extraction.text import TfidfVectorizer


tfidf = TfidfVectorizer(stop_words='english')


df2['overview'] = df2['overview'].fillna('')


tfidf_matrix = tfidf.fit_transform(df2['overview'])


tfidf_matrix.shape

(4803, 20978)

In [6]:

from sklearn.metrics.pairwise import linear_kernel


cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [7]:
indices = pd.Series(df2.index, index=df2['title']).drop_duplicates()

In [8]:

def get_recommendations(title, cosine_sim=cosine_sim):
    
    idx = indices[title]

    
    sim_scores = list(enumerate(cosine_sim[idx]))

    
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    
    sim_scores = sim_scores[1:11]

    
    movie_indices = [i[0] for i in sim_scores]

 
    return df2['title'].iloc[movie_indices]

In [9]:
get_recommendations('The Dark Knight Rises')

65                              The Dark Knight
299                              Batman Forever
428                              Batman Returns
1359                                     Batman
3854    Batman: The Dark Knight Returns, Part 2
119                               Batman Begins
2507                                  Slow Burn
9            Batman v Superman: Dawn of Justice
1181                                        JFK
210                              Batman & Robin
Name: title, dtype: object

In [23]:
get_recommendations('Anaconda')

3992                      Sardaarji
3090              Cecil B. Demented
1137              One for the Money
4735              The Night Visitor
2527    National Lampoon's Vacation
1041                        Taken 2
3113      Cinco de Mayo: La Batalla
950                  The Negotiator
2360                        Getaway
538                         Hostage
Name: title, dtype: object